name: Refresh Data
on:
  schedule:
    - cron: '0 * * * *'    # Runs every hour at 00 minutes
    - cron: '59 23 * * *'  # Runs 1 minute before midnight
jobs:
  refresh-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pytz
      - name: Run script
        run: python main.py
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add user_xp_data.json
          git commit -m "Update data" || echo "No changes to commit"
      - name: Pull changes from remote
        run: git pull origin master
      - name: Push changes
        run: git push https://${{ secrets.REPO_ACCESS_TOKEN }}@github.com/Megasteel32/duolingoleaderboard.git